### ISSUE TITLE
Image are always flagged

### ISSUE THREAD

**Issue by ebw44** [dlyz/md-link-checker#2]
`![image info](./pictures/image.png)` is flagged with 
```
Link definition for 'image info' not found.
If this is not a link reference, consider bracket escaping '\\[' or using code block."
```

**Comment by dlyz** [comment]
Sorry for quite a delay. I can not reproduce this problem. If it is still important for you, feel free to provide more information and reopen the issue.

Also note that I have no intentions to actively support this project, more information provided at the top of the readme.

**Comment by ebw44** [comment]
I'm not using the extension anymore as the features I was using have been integrated into vscode.

Thanks anyway as it was a really useful extension.
